//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_ticket_serie
    {
        public int id { get; set; }
        public string ticket_type { get; set; }
        public string ticket_serie { get; set; }
        public int start_number_serie { get; set; }
        public int end_number_serie { get; set; }
        public int staff_id { get; set; }
    }
}
