//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_review_history
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> center_archives_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string lpn { get; set; }
    }
}
