//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_lane
    {
        public string id { get; set; }
        public string lane_name { get; set; }
        public Nullable<double> lane_width { get; set; }
        public Nullable<double> lane_height { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
