//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_ticket_cancel
    {
        public int id { get; set; }
        public string ticket_name { get; set; }
        public string ticket_type { get; set; }
        public string ticket_serie { get; set; }
        public int start_number_serie { get; set; }
        public int end_number_serie { get; set; }
        public Nullable<System.DateTime> date_cancel { get; set; }
        public Nullable<int> quantity { get; set; }
        public string from_staff_fullname { get; set; }
        public Nullable<int> from_staff { get; set; }
        public string cancel_user_fullname { get; set; }
        public Nullable<int> cancel_user { get; set; }
        public string reasons { get; set; }
        public Nullable<bool> is_sales { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<System.DateTime> sell_time { get; set; }
    }
}
