//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_archives
    {
        public int id { get; set; }
        public Nullable<byte> station_id { get; set; }
        public string lance_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<byte> session_id { get; set; }
        public Nullable<byte> error_id { get; set; }
        public string lpn { get; set; }
        public string barcode { get; set; }
        public Nullable<byte> barcode_type { get; set; }
        public string plateimage_filename { get; set; }
        public string fullimage_filename { get; set; }
        public Nullable<byte> classify_type { get; set; }
        public Nullable<decimal> ticket_value { get; set; }
        public string ticket_type { get; set; }
        public Nullable<System.DateTime> start_boarding_time { get; set; }
        public Nullable<System.DateTime> end_boarding_time { get; set; }
        public Nullable<decimal> loading_capacity { get; set; }
        public Nullable<System.DateTime> last_update_time { get; set; }
        public Nullable<short> last_update_userID { get; set; }
        public Nullable<short> observer_id { get; set; }
        public string history { get; set; }
        public Nullable<short> approved_id { get; set; }
        public Nullable<bool> @checked { get; set; }
    }
}
