//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_ticket_prepay
    {
        public int id { get; set; }
        public string lpn { get; set; }
        public byte classify_type { get; set; }
        public byte ticket_type { get; set; }
        public Nullable<decimal> ticket_value { get; set; }
        public string barcode { get; set; }
        public string classify_owner { get; set; }
        public Nullable<System.DateTime> validity_start_date { get; set; }
        public Nullable<System.DateTime> validity_end_date { get; set; }
        public Nullable<byte> accounting_staffid { get; set; }
        public string payment { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string update_history { get; set; }
    }
}
