//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_ticket_store
    {
        public int id { get; set; }
        public string ticket_serie { get; set; }
        public string ticket_name { get; set; }
        public string ticket_type { get; set; }
        public int start_number_serie { get; set; }
        public int end_number_serie { get; set; }
        public Nullable<System.DateTime> date_store { get; set; }
        public Nullable<bool> outForSale { get; set; }
        public Nullable<System.DateTime> date_out { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> book_number { get; set; }
    }
}
