//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_station
    {
        public byte id { get; set; }
        public string station_name { get; set; }
        public string barcode_prefix { get; set; }
        public Nullable<int> ticketone { get; set; }
        public Nullable<int> ticketmonth { get; set; }
        public Nullable<int> ticketquarter { get; set; }
        public Nullable<int> ticketturnhighway { get; set; }
        public Nullable<int> ticketprioritygroup { get; set; }
        public Nullable<int> ticketmember { get; set; }
        public Nullable<byte> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string hederReport { get; set; }
        public Nullable<int> ticketnation { get; set; }
        public Nullable<int> ticketperiod { get; set; }
        public Nullable<int> ticketprioritysingle { get; set; }
    }
}
