//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_employee
    {
        public int id { get; set; }
        public string uname { get; set; }
        public string password { get; set; }
        public string user_barcode { get; set; }
        public string image_text { get; set; }
        public string displayname { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> isCabin { get; set; }
        public Nullable<bool> isSupervisor { get; set; }
        public Nullable<bool> isAccountant { get; set; }
        public Nullable<bool> isLeader { get; set; }
        public Nullable<bool> isElectric { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> isCashier { get; set; }
        public Nullable<bool> isLaneDivision { get; set; }
        public Nullable<bool> isOfficeWork { get; set; }
        public Nullable<bool> isDirector { get; set; }
    }
}
