//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_ticket_delivery
    {
        public int id { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string deliveryer_name { get; set; }
        public Nullable<int> deliveryer { get; set; }
        public string receiver_name { get; set; }
        public Nullable<int> receiver { get; set; }
        public string ticket_name { get; set; }
        public string ticket_type { get; set; }
        public int quantity { get; set; }
        public Nullable<int> startSerie { get; set; }
        public Nullable<int> endSerie { get; set; }
        public string ticketSerie { get; set; }
        public Nullable<int> session_id { get; set; }
    }
}
