//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_ticket_type
    {
        public string id { get; set; }
        public string ticket_name { get; set; }
        public decimal ticket_value { get; set; }
        public Nullable<byte> ticket_type { get; set; }
        public byte classify_type { get; set; }
        public string payment { get; set; }
        public string descriptions { get; set; }
    }
}
