//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class center_plate_Update_History
    {
        public int id { get; set; }
        public string lpn { get; set; }
        public Nullable<int> oldClassifyType { get; set; }
        public Nullable<int> newClassifyType { get; set; }
        public Nullable<int> userId { get; set; }
        public string userFullName { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
