//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TS_CENTEREntities : DbContext
    {
        public TS_CENTEREntities()
            : base("name=TS_CENTEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<center_archives> center_archives { get; set; }
        public virtual DbSet<center_archives_manual> center_archives_manual { get; set; }
        public virtual DbSet<center_employee> center_employee { get; set; }
        public virtual DbSet<center_lane> center_lane { get; set; }
        public virtual DbSet<center_operation_error> center_operation_error { get; set; }
        public virtual DbSet<center_plate> center_plate { get; set; }
        public virtual DbSet<center_plate_Update_History> center_plate_Update_History { get; set; }
        public virtual DbSet<center_review_history> center_review_history { get; set; }
        public virtual DbSet<center_staff_error> center_staff_error { get; set; }
        public virtual DbSet<center_station> center_station { get; set; }
        public virtual DbSet<center_ticket_cancel> center_ticket_cancel { get; set; }
        public virtual DbSet<center_ticket_delivery> center_ticket_delivery { get; set; }
        public virtual DbSet<center_ticket_delivery_Copy> center_ticket_delivery_Copy { get; set; }
        public virtual DbSet<center_ticket_prepay> center_ticket_prepay { get; set; }
        public virtual DbSet<center_ticket_restore> center_ticket_restore { get; set; }
        public virtual DbSet<center_ticket_serie> center_ticket_serie { get; set; }
        public virtual DbSet<center_ticket_store> center_ticket_store { get; set; }
        public virtual DbSet<center_ticket_type> center_ticket_type { get; set; }
        public virtual DbSet<etc_archives> etc_archives { get; set; }
        public virtual DbSet<ETCMark> ETCMarks { get; set; }
        public virtual DbSet<station_log> station_log { get; set; }
        public virtual DbSet<station_paramater> station_paramater { get; set; }
        public virtual DbSet<station_session> station_session { get; set; }
        public virtual DbSet<store_endofsession> store_endofsession { get; set; }
        public virtual DbSet<store_endofsession_money> store_endofsession_money { get; set; }
        public virtual DbSet<ticket_history> ticket_history { get; set; }
    }
}
