//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class etc_archives
    {
        public int id { get; set; }
        public Nullable<byte> station_id { get; set; }
        public string lane_id { get; set; }
        public Nullable<short> user_id { get; set; }
        public string lpn { get; set; }
        public Nullable<byte> plate_type { get; set; }
        public Nullable<byte> transaction_type { get; set; }
        public string lpn_image { get; set; }
        public string overview_image { get; set; }
        public Nullable<byte> vehicle_type { get; set; }
        public Nullable<decimal> ticket_value { get; set; }
        public string ticket_type { get; set; }
        public Nullable<System.DateTime> start_boarding_time { get; set; }
        public Nullable<System.DateTime> end_boarding_time { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<bool> revised { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
