//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_session
    {
        public byte id { get; set; }
        public string session_name { get; set; }
        public System.DateTime session_start_time { get; set; }
        public System.DateTime session_end_time { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<byte> session_order { get; set; }
    }
}
