//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_endofsession
    {
        public int id { get; set; }
        public string staff { get; set; }
        public string ticket_type { get; set; }
        public int quantity_before { get; set; }
        public int quantity_sale { get; set; }
        public int quantity_after { get; set; }
        public string series_after { get; set; }
        public System.DateTime date_work { get; set; }
        public int session_work { get; set; }
        public short staff_id { get; set; }
        public Nullable<int> quantity_getin { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<System.DateTime> real_time { get; set; }
    }
}
