//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_endofsession_money
    {
        public int id { get; set; }
        public string staff { get; set; }
        public int money_before { get; set; }
        public int money_after { get; set; }
        public System.DateTime date_work { get; set; }
        public int session_work { get; set; }
        public short staff_id { get; set; }
    }
}
