//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseTollPlaza.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket_history
    {
        public int id { get; set; }
        public string ticket_name { get; set; }
        public string ticketID { get; set; }
        public Nullable<byte> ticket_type { get; set; }
        public Nullable<byte> vehicle_type { get; set; }
        public Nullable<decimal> ticket_value { get; set; }
        public Nullable<System.DateTime> validate_start { get; set; }
        public Nullable<System.DateTime> validate_end { get; set; }
        public string note { get; set; }
    }
}
